### ISSUE TITLE
日志报get access token failed

### ISSUE THREAD

**Issue by benvyeng** [easychen/botchan#3]
![de1e787d5faf41706b36a558325bb98](https://github.com/easychen/botchan/assets/56990900/c05b546f-8b77-4ecd-b06c-c64adf2f8635)
目前就是测试号可以收到消息，但是无回复，/help可以回复而且设置也生效，就是无法正常发送GPT生成消息，求解

**Comment by easychen** [comment]
这是微信测试号平台的Bug，尤其是对于刚开通的。可以试试手动退出微信测试号平台，重新扫码登录，查看 appsecret 是不是变了，然后改用新的 appsecret 。

**Comment by benvyeng** [comment]
> 这是微信测试号平台的Bug，尤其是对于刚开通的。可以试试手动退出微信测试号平台，重新扫码登录，查看 appsecret 是不是变了，然后改用新的 appsecret 。

确实变了，这个好坑啊
