### ISSUE TITLE
docker 已经启动 但是接口配置信息提交的时候提示配置失败

### ISSUE THREAD

**Issue by zccyx** [easychen/botchan#9]
![image](https://github.com/easychen/botchan/assets/26381587/ea833744-c0c2-4f14-935a-1fb90340e7b3)

**Comment by zccyx** [comment]
这样子容器是已经启动成功了吧
![image](https://github.com/easychen/botchan/assets/26381587/496a818b-b62d-498f-b26d-5502ee04f69f)

**Comment by easychen** [comment]
token 填错了。

**Comment by zccyx** [comment]
> token 填错了。
填的是 docker命令里 MP_TOKEN= 的值，应该没有错，就是6位的全英文字母

**Comment by easychen** [comment]
> > token 填错了。
> > 填的是 docker命令里 MP_TOKEN= 的值，应该没有错，就是6位的全英文字母

你的错误信息显示，Token 错了。至于什么地方错了，请仔细阅读文档检查配置。包括微信的文档，查一下那个106。
